python internal_consistency/response_collection.py
python internal_consistency/split_into_files.py
python internal_consistency/equation_collection.py
python internal_consistency/adam_smasher.py
@REM python internal_consistency/solve_equations.py
python internal_consistency/system_equation_collection.py